### ISSUE TITLE
Getting JSON data to influxDB

### ISSUE THREAD

**Issue by kisienya** [chrisfauerbach/suricata_stats_influx#1]
Hi Chris, thanks,

This is very good work.

Just wondering how you managed to get JSON data to influxDB because the current version of InfluxDB doesn’t support the JSON . The predominant reason it was deprecated was that decoding JSON was the largest performance bottleneck in the system.

See https://github.com/influxdata/influxdb/pull/2696#issuecomment-106968181

**Comment by chrisfauerbach** [comment]
Please read my blog post here about it.  I use Logstash to inject JSON data into Influx.  Might not be the most performant, but it works for my use case perfectly.

https://fauie.com/2016/06/27/suricata-stats-to-influx-dbgrafana/
