### ISSUE TITLE
InfluxDB inputs configuration

### ISSUE THREAD

**Issue by kisienya** [chrisfauerbach/suricata_stats_influx#2]
Hi Christ,

Kindly elaborate on how you configured your influxDB inputs to read data from logstash.

I have logstash.conf file well populated and configtest shows OK. My logstash.log file also shows "message=>"Pipeline main started". So all is ok with logstash. 

However influxDb is not populating.

Kindly assist.

Cheers

**Comment by chrisfauerbach** [comment]
Added the logstash config file here.    This is pretty much as far as I can help you.  If this doesn't work, I don't really know what to tell you.  I'm by no stretch an Influx expert.

I can point you to the 'ruby debug' output for Logstash. It might help

https://github.com/chrisfauerbach/suricata_stats_influx/blob/master/src/suricata_to_influx.conf
